version: '3.8'

services:
  udtoolapi:
    build:
      context: .
      dockerfile: UDToolAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
